In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [3]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()
X_train_std = standardizer.fit_transform(X_train)

In [4]:
# Salida de resultados.
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
